apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dockerwalkthrough
  namespace: argocd
spec:
  project: default
  source:
    path: .
    repoURL: oci://ghcr.io/sergioacortes/charts/dockerwalkthrough
    targetRevision: 0.5.0-rev.1
    helm:
      releaseName: dockerwalkthrough
      values: |
        service:
          type: NodePort
        image:
          tag: 0.5.0-rev.1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
