apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dockerwalkthroughprivate
  namespace: argocd
spec:
  project: default
  source:
    path: .
    repoURL: oci://ghcr.io/sergioacortes/charts
    chart: dockerwalkthroughprivate
    targetRevision: 0.1.0-rev.1
    helm:
      releaseName: dockerwalkthroughprivate
      values: |
        service:
          type: NodePort
        image:
          tag: 0.1.0-rev.1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
