apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dockerwalkthrough
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'oci://ghcr.io/sergioacortes/'
    chart: 'charts/dockerwalkthrough'
    targetRevision: 0.0.1-42
    helm:
      releaseName: dockerwalkthrough
      values: |
        service:
          type: NodePort
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
