apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/sergioacortes/charts
    chart: docker-java
    targetRevision: 0.2.0-rev.1
    helm:
      releaseName: docker-java
      values: |
        namespace: dev
        replicaCount: 3
        service:
          type: NodePort
        image:
          repository: ghcr.io/sergioacortes/images/docker-java
          tag: 0.2.0-rev.1
        livenessProbe:
          httpGet:
            path: /api/livez
        readinessProbe:
          httpGet:
            path: /api/readyz
        # imagePullSecrets:
        #   - name: ghcr-credentials
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
